### ISSUE TITLE
run_to_position

### ISSUE THREAD

**Issue by Usimian** [jweiland1/VRS-Bug-Report#3]
Tried changing rear motor directions to strafe but it appears to be running in two wheel drive mode thus it will only turn or fwd/bwd.
How to make it strafe?
The examples for run_to_position all use power instead of velocity, why?

**Comment by jweiland1** [comment]
Did you run with 4 motors https://somup.com/c3X11Uv5LF   
![image](https://user-images.githubusercontent.com/23490327/200157567-9dd701c7-a845-4aa3-9b63-806510184260.png)

Why power?  I understand power- velocity likely works

**Comment by jweiland1** [comment]
see  you can use velocity
https://somup.com/c3X11av5Lt
![image](https://user-images.githubusercontent.com/23490327/200157638-952e029b-dc08-4e50-ba1e-5641dfc0445a.png)

**Comment by Usimian** [comment]
Yes, but I changed the motor direction on two of the motors in order to
strafe but it's not working.
I'm following the REV encoder document which recommends using velocity and
not power when using run_to_position.
The PID controller takes care of setting power.  Thanks for responding.

**Comment by Usimian** [comment]
Here's the document I'm using.
Using Encoders - DUO Control System
<https://docs.revrobotics.com/duo-control/programming/using-encoder-feedback>

**Comment by scalidas** [comment]
Velocity and power should both work for run_to_position. I am not sure if the simulator supports setVelocity(). Can you try replacing those blocks with setPower() and see if that works? Also make sure that frontRight and backRight are reversed on initialization. Also do make sure that you are setting the correct motor powers according to the diagram below.

![image](https://user-images.githubusercontent.com/84115793/200390891-466967c1-774a-4d67-ac23-e4941f8d7a39.png)

**Comment by Usimian** [comment]
I see the issue.
In run_to_position mode using set velocity, the *motor direction is ignored*.
It always moves forward.
However, I can get it to strafe by making the target position for the front
left & back right wheels to the negative of the target position.
With a PID algorithm, you generally set velocity and let the algorithm
adjust power.
This approach is more efficient on the hardware robot and eliminates the
sleep timer in favor of checking motor.isBusy.

This will cause a left strafe.
[image: image.jpeg]

Thanks for looking at this.  The simulator is great for the students.


Marc

**Comment by jweiland1** [comment]
Marc have you considered getting your teacher robot inserted? I only need a
fbx file, and maybe a video of your animated joints.

**Comment by jweiland1** [comment]
Thanks. If you feel motivated (and hopefully positive), can you post
something about the vrs. I could use some exposure.
